# Generated by Django 4.1 on 2022-08-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choices",
            name="author_info",
        ),
    ]
