# Generated by Django 4.1 on 2022-08-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_choices_author_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="choices",
            name="number_of_times_selected",
            field=models.IntegerField(default=0),
        ),
    ]
