# Generated by Django 4.1 on 2022-08-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="datetime_of_publication",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="datetime_of_publication"
            ),
        ),
    ]
